
# MongoDB connection string (default localhost:27017)
quarkus.mongodb.connection-string=mongodb://localhost:27017

# Name of the database to use
quarkus.mongodb.database=NearByFriends

# Enable Liquibase MongoDB migrations at startup
quarkus.liquibase-mongodb.migrate-at-start=true

## Specify the changelog file location (optional if using default)
quarkus.liquibase-mongodb.change-log=db.changelog/changelog-collections.yaml

quarkus.datasource.devservices.enabled=false


