# Enable HTTP Basic Authentication
quarkus.http.auth.basic=true

# Datasource Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=test@1234
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Quarkus

# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=update


